[package]
name = "turmoil"
version = "0.1.0"
edition = "2018"
license = "MIT"
resolver = "2"

[dependencies]
crossbeam-channel = "0.5.1"
crossterm = "0.19.0"
thiserror = "1.0.26"
tui = { version = "0.15.0", default-features = false, features = ["crossterm"] }
